### ISSUE TITLE
Speeding up landscape.setallelefreq()

### ISSUE THREAD

**Issue by EricArcher** [stranda/rmetasim#10]
I've been doing runs with the new `landscape.setpopfreq()` function and have noticed that for large landscapes, (e.g.,  five populations with 1000 individuals each), it runs very slowly. It seems like it can take up to an hour or more to set up the landscape on my MacBook Pro. I've done some profiling and it seems like the speed hit is related to multiple calls to `is.landscape()` in the nested for loop in `landscape.setallelefreq()` that calls `landscape.locus.states()`. 
What do you think of having another parameter to `is.landscape()` that is something like `perform.check = TRUE`. All functions that use it can take and pass this argument on and perform all checks by default, but if it is in a loop and doesn't need to be done each time, this can be set to `FALSE` and the first line is something simple, like 

`if(!perform.check) return(TRUE)`

**Comment by stranda** [comment]
Sorry to hear about the speed issue.  

I went ahead and made your suggested changes.  I called the parameter for is.landscape() 'do.check' (you know I hate to type).  Right now the only function that uses the new option is landscape.locus.states() and it is set false in the landscape.setallelefreq() function. 

This is up on github and didn't crash when I tried the examples for  landscape.setallelefreq() 

let me know what you think
cheers,
a.

**Comment by EricArcher** [comment]
You da man! That is working, but it looks like `is.landscape()` is also being called by `landscape.locus()` which is in `landscape.locus.states()`. Adding `do.check = F` there should do the trick.
Thanks bud!

**Comment by stranda** [comment]
errp.  Give the new commit a try.
a.

**Comment by EricArcher** [comment]
Like butter running down a biscuit. Perfect.
Thanks a ton for whipping that out so fast.
-e

**Comment by thierrygosselin** [comment]
very nice! can't wait to try
