### ISSUE TITLE
Separate allele frequencies for each population

### ISSUE THREAD

**Issue by EricArcher** [stranda/rmetasim#9]
Allan,
I'm getting back to setting up some `rmetasim` simulations. I'm using it to condition `fastsimcoal2` simulations over a few generations to establish linkage disequilibrium. As such, I'd like to specify allele frequencies for each population separately, but I can't seem to work out if that's possible. The ability doesn't seem to be part of `rmetasim::landscape.new.locus()`. I thought it used to be in `rmetasim::landscape.new.individuals()`, but that seems to only take the number of individuals in stages and populations now. Is this possible in the current version?

Cheers,
Eric

**Comment by stranda** [comment]
Hi Eric,

Yes, I just wrote it to allow specification of global allele freqs.  I have written custom routines over the years that implement population (really stage) specific allele frequency specification.  I could code up a function to do what you want pretty easily based on this previous effort and fold it into the rmetasim codebase.  I'm pretty sure though, that the most expedient approach I would take would be 1) for you to create a landscape, specify the demography, loci and global allele frequencies and 2) use the function I'm thinking about to modify that landscape after it was created.  I'm thinking the function would take a landscape and a list of populations each of which is comprised of a list of named vectors that is the same length as the number of loci.  The named vectors would use the names as allele states and the elements as frequencies.

Does that workflow and parameterization work for you?   

cheers,
allan

**Comment by EricArcher** [comment]
Thanks Allan. I think that would work. What I have as input is population-specific frequencies for a set of SNPs.

Side-question: Is there still a pre-compiled hard limit on the number of loci in a landscape?

**Comment by stranda** [comment]
So I wrote a couple of functions.  landscape.setallelefreq() will set allele frequencies in any arbitrary stage.  More important to your use case is landscape.setpopfreq() which sets allele freqs for any population and locus combination (it's really a frontend for the former function listed above).

You'll have to install from github, I have not tried to submit to CRAN yet.  There are help pages for both functions and the examples also show the structure of the list of lists that's required for an input parameter.

Let me know how it works and also if there are helper functions that would ease creating the lists.

Finally, yes the # of loci is hard-coded; currently set at 1000.

cheers,
a.

**Comment by EricArcher** [comment]
Thanks Allan! This looks like it'll do what I need. I'll give it a test drive soon. 
FYI: This is for both the GEO-BON EBV simulations and a project on assessing missing data imputation methods I'm working with Thierry Gosselin on.

**Comment by thierrygosselin** [comment]
I'm changing the number of loci this way:
https://thierrygosselin.github.io/grur/articles/rad_genomics_computer_setup.html#rmetasim

**Comment by EricArcher** [comment]
I do the same. I just wanted to make sure that Allan hadn't changed it so it could be done dynamically.

**Comment by EricArcher** [comment]
Allan, Just wanted to let you know that I finally got around to testing out `landscape.setpopfreq()` and it works just like we needed. Thanks again!
